server:
  port: 8086
spring:
  application:
    name: graph-recipe
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    path: /sathish_runs
  datasource:
    url: ${garmindb}
    driverClassName: org.postgresql.Driver
    username: ${darmindb_user}
    password: ${darmindb_password}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
management:
  endpoint:
    health:
      show-details: always
